# Generated by Django 5.2.7 on 2025-12-02 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ⛔ Removido: RemoveField 'evento' (não existe mais)
        # ⛔ Removido: AlterUniqueTogether de Inscricao
        # ⛔ Removido: RemoveField 'usuario' (não existe mais)

        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('event_type', models.CharField(choices=[('seminario', 'Seminário'), ('palestra', 'Palestra'), ('workshop', 'Workshop'), ('curso', 'Curso')], max_length=50, verbose_name='Tipo')),
                ('start_date', models.DateField(verbose_name='Data início')),
                ('end_date', models.DateField(verbose_name='Data fim')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Horário início')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Horário fim')),
                ('location', models.CharField(max_length=255, verbose_name='Local')),
                ('capacity', models.PositiveIntegerField(verbose_name='Vagas')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Banner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
                ('professor_in_charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events_as_professor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('presence_confirmed', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='eventos.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_at'],
                'unique_together': {('user', 'event')},
            },
        ),

        # ⛔ Removido: DeleteModel Evento e Inscricao
        # Porque eles provavelmente já não existem mais no banco/migração real.
    ]
