# Generated by Django 5.2.7 on 2025-12-04 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_remove_inscricao_evento_and_more'),
    ]

    operations = [
        # Use raw SQL to drop old tables if they exist
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS eventos_inscricao;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS eventos_evento;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
