# Generated by Django 5.2.7 on 2025-12-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='instituicao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefone',
        ),
        migrations.AddField(
            model_name='usuario',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instituição'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor'), ('organizador', 'Organizador')], default='aluno', max_length=20, verbose_name='Perfil'),
            preserve_default=False,
        ),
    ]
